### ISSUE TITLE
Epic Mesh4all Documentation Review

### ISSUE THREAD

**Issue by CW-75** [Mesh4all/Mesh4all#8]
It's necessary to correctly maintain the documentation structure of the repository.
This adds more aesthetics to the repository that we are working.

- [x] README review
- [x] CODING_CONVENTION.md
- [x] CONTRIBUTING.md
- [x] CONTRIBUTORS
- [x] CODE_OF_CONDUCT.md
- [ ] Repository Labels Review
